package com.olamide.findartt.enums;


public enum ErrorCode {
    TOKEN_NOT_FOUND,RESOURCE_NOT_FOUND, ENTITY_NOT_FOUND,
    INVALID_USERNAME_PASSWORD, USER_NOT_VERIFIED,
    VALIDATION_ERROR,ERROR,
}
